# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUJN7OIoFui_vpej_9F1oWQXipZftYF3
"""

Faltas= int(input("Digite seu número de faltas: "))
Total_aulas = int(input("Digite o número total de aulas que você tem: "))
if Faltas > (0.25*Total_aulas):
  print("Reprovado por faltas.")
else:
  print("presença suficiente.")

tem_documento = input("Tem documento? (s/n): ").strip().lower() == "s"
idade = int(input("Idade: "))

if not tem_documento:
 print("Não entrar (sem documento)")
elif idade >= 16:
 print("Entrar")
else:
 print("Não entrar (menor de 16)")

tem_documento = input("Tem documento? (s/n): ").strip().lower() == "s"
idade = int(input("Idade: "))

if not tem_documento:
 print("Não entrar (sem documento)")
elif idade >= 16:
 print("Entrar")
else:
 print("Não entrar (menor de 16)")

tem_documento = input("Tem documento? (s/n): ").strip().lower() == "s"
idade = int(input("Idade: "))

if not tem_documento:
 print("Não entrar (sem documento)")
elif idade >= 16:
 print("Entrar")
else:
 print("Não entrar (menor de 16)")

tem_documento = input("Tem documento? (s/n): ").strip().lower() == "s"
idade = int(input("Idade: "))

if not tem_documento:
 print("Não entrar (sem documento)")
elif idade >= 16:
 print("Entrar")
else:
 print("Não entrar (menor de 16)")

for _ in range(25):
  print("Olá, mundo")

for i in range(5):
  print(i)

for i in range(5):
  print(i + 1)

for i in range(1, 6):
  print(i)

for i in range(0,11, 8):
  print(i)

"""DESAFIO 1: mostre os números de 2 a 20 na tela:"""

for i in range(2, 20):
  print(i+1)

"""DESAFIO 2: imprimir 5,4,3,2,1 e ao final"Lançar!".
Dica: range aceita passo negativo.
"""

for i in range(5, 0, -1):
  print(i)
if 1 == 1:
  print("Lançar!")

nome = input("digite o seu nome:")
for _ in range(10):
    print(nome)

for i in range(1,20):
 print(i+1)

print("Tabuada do 5:")
for i in range(1, 11):
  print(f"5 x {i} = {5 * i}")

palavra = input("Digite uma palavra: ")

print("Cada letra da palavra:")
for letra in palavra:
    print(letra)

n=5
while n>0:
 print(n)
 n+=1
print("lançar!")

senha_correta = "python123"
senha = input("digite a senha: ")

while senha != senha_correta:
  print("senha incorreta. tente novamente.")
  senha = input("digite a senha: ")

print("acesso liberado.")

valor = float(input("digite um número positivo: "))
while valor <= 0:
  print("valor invàlido.")
  valor = float(input("tente de novo (positivo): "))
print("valor aceito: ", valor)

print("Some números; digite 0 para encerrar.")
soma = 0
num = float(input("números: "))

while num !=0:
  soma += num
  num = float(input("número"))

print("soma total = ", soma)

frutas=["maça", "banana", "laranja"]

notas=[8.5, 7.0, 10.0]

print(frutas[0])
print(frutas[1])
print(notas)

frutas.append("uva")
print(frutas)

frutas.remove("banana")
print(frutas)

compras = ["maçã", "uva", "banana", "melancia"]
print(compras[0])
print(compras[-1])

alunos = ["ana", "bruno", "carlos"]
print(alunos[0])
alunos.append("diana")
alunos.remove("bruno")
print(len(alunos))
print(alunos)

notas = [7.0, 8.5, 9.5]
soma = sum(notas)
media = soma / len(notas)
print(media)

texto = "a viagem foi massa"
texto_alterado = texto.replace("massa","incrível")
print(texto_alterado)

texto = "Eu Acho PYTHON Muito Legal"
texto_alterado = texto.lower()
texto_alterado = texto_alterado.replace("phyton", "phyton")
print(texto_alterado)

Nome_usuario = " Ana silva "
email = "Ana@email.com"

nome_tratado = Nome_usuario.strip()
email_tratado = email.lower()

if nome_tratado != Nome_usuario:
  print("Nome contém espaços extras.")
elif email != email_tratado:
  print("E-mail deve conter apenas letras minúsculas")
else:
  print("dados válidos")

if "@" in email_tratado:
  print("E-mail válido")
else:
  print("E-mail inválido")

senha = "12345"

tamanho = len(senha)

if tamanho < 8:
  print("Senha muito curta")
else:
  print("Senha válida")

texto = input("Mensagem: ")
mensagem_tratada = texto.strip()
tamanho = len(mensagem_tratada)
if tamanho > 100:
  print("É muito grande :(")
else:
  print("Post enviado :)")

post = "Olá mundo!"

tamanho = len(post)

if tamanho < 10:
  faltam = 10 - tamanho
  print(f"Post muito curto. Faltam {faltam} caracteres.")
elif tamanho > 100:
  excedeu = tamanho - 100
  print(f"post muito longo. Ultrapassou {excedeu} caracteres.")
else:
  print("Post publicado :)")

v bmhfgjuyrtiy xr467c ¬76.çpityre8trucfgkiufyj d54 y5